import { beforeEach, describe, expect, it, vi } from "vitest";

const { handle } = vi.hoisted(() => ({ handle: vi.fn() }));
vi.mock("@tanstack/react-start/server-entry", () => ({
  default: { fetch: handle },
}));
import server from "@/server";

beforeEach(() => {
  handle.mockReset();
  handle.mockResolvedValue(new Response("ok", { status: 200 }));
});

describe("hosting owns domain redirects", () => {
  it.each([
    ["GET", "https://realityscanner.cz/"],
    ["HEAD", "https://realityscanner.cz/"],
    ["GET", "https://realityscanner.cz/cenik?checkout=success"],
    ["GET", "https://www.realityscanner.cz/"],
    ["GET", "https://preview.lovable.app/"],
    ["POST", "https://realityscanner.cz/api/public/stripe/webhook"],
    ["GET", "https://realityscanner.cz/_serverFn/test"],
  ])("passes %s %s to the application without redirecting", async (method, url) => {
    const request = new Request(url, { method });
    const response = await server.fetch(request, {}, {});
    expect(response.status).toBe(200);
    expect(response.headers.get("location")).toBeNull();
    expect(handle).toHaveBeenCalledWith(request, {}, {});
  });

  it("preserves redirects generated by the application (e.g. authentication)", async () => {
    handle.mockResolvedValue(Response.redirect("https://realityscanner.cz/auth", 302));
    const response = await server.fetch(new Request("https://realityscanner.cz/saved"), {}, {});
    expect(response.status).toBe(302);
    expect(response.headers.get("location")).toBe("https://realityscanner.cz/auth");
  });
});
