/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as ObchodniPodminkyRouteImport } from './routes/obchodni-podminky'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWatchdogsRouteImport } from './routes/_authenticated/watchdogs'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedNastaveniInvestoraRouteImport } from './routes/_authenticated/nastaveni-investora'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicHooksRunSchedulesRouteImport } from './routes/api/public/hooks/run-schedules'
import { Route as ApiPublicCronScrapeSrealityRouteImport } from './routes/api/public/cron/scrape-sreality'
import { Route as ApiPublicCronScrapeRealitymixRouteImport } from './routes/api/public/cron/scrape-realitymix'
import { Route as ApiPublicCronScrapeIdnesRouteImport } from './routes/api/public/cron/scrape-idnes'
import { Route as ApiPublicCronScrapeHyperinzerceRouteImport } from './routes/api/public/cron/scrape-hyperinzerce'
import { Route as ApiPublicCronScrapeBezrealitkyRouteImport } from './routes/api/public/cron/scrape-bezrealitky'
import { Route as ApiPublicCronScrapeBazosRouteImport } from './routes/api/public/cron/scrape-bazos'
import { Route as ApiPublicCronScrapeAnnonceRouteImport } from './routes/api/public/cron/scrape-annonce'
import { Route as ApiPublicCronHealthCheckRouteImport } from './routes/api/public/cron/health-check'
import { Route as ApiPublicCronDailyDigestRouteImport } from './routes/api/public/cron/daily-digest'

const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodniPodminkyRoute = ObchodniPodminkyRouteImport.update({
  id: '/obchodni-podminky',
  path: '/obchodni-podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchdogsRoute = AuthenticatedWatchdogsRouteImport.update({
  id: '/watchdogs',
  path: '/watchdogs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNastaveniInvestoraRoute =
  AuthenticatedNastaveniInvestoraRouteImport.update({
    id: '/nastaveni-investora',
    path: '/nastaveni-investora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunSchedulesRoute =
  ApiPublicHooksRunSchedulesRouteImport.update({
    id: '/api/public/hooks/run-schedules',
    path: '/api/public/hooks/run-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeSrealityRoute =
  ApiPublicCronScrapeSrealityRouteImport.update({
    id: '/api/public/cron/scrape-sreality',
    path: '/api/public/cron/scrape-sreality',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeRealitymixRoute =
  ApiPublicCronScrapeRealitymixRouteImport.update({
    id: '/api/public/cron/scrape-realitymix',
    path: '/api/public/cron/scrape-realitymix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeIdnesRoute =
  ApiPublicCronScrapeIdnesRouteImport.update({
    id: '/api/public/cron/scrape-idnes',
    path: '/api/public/cron/scrape-idnes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeHyperinzerceRoute =
  ApiPublicCronScrapeHyperinzerceRouteImport.update({
    id: '/api/public/cron/scrape-hyperinzerce',
    path: '/api/public/cron/scrape-hyperinzerce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeBezrealitkyRoute =
  ApiPublicCronScrapeBezrealitkyRouteImport.update({
    id: '/api/public/cron/scrape-bezrealitky',
    path: '/api/public/cron/scrape-bezrealitky',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeBazosRoute =
  ApiPublicCronScrapeBazosRouteImport.update({
    id: '/api/public/cron/scrape-bazos',
    path: '/api/public/cron/scrape-bazos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeAnnonceRoute =
  ApiPublicCronScrapeAnnonceRouteImport.update({
    id: '/api/public/cron/scrape-annonce',
    path: '/api/public/cron/scrape-annonce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHealthCheckRoute =
  ApiPublicCronHealthCheckRouteImport.update({
    id: '/api/public/cron/health-check',
    path: '/api/public/cron/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyDigestRoute =
  ApiPublicCronDailyDigestRouteImport.update({
    id: '/api/public/cron/daily-digest',
    path: '/api/public/cron/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cenik': typeof CenikRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/health': typeof AuthenticatedHealthRoute
  '/nastaveni-investora': typeof AuthenticatedNastaveniInvestoraRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/watchdogs': typeof AuthenticatedWatchdogsRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/scrape-annonce': typeof ApiPublicCronScrapeAnnonceRoute
  '/api/public/cron/scrape-bazos': typeof ApiPublicCronScrapeBazosRoute
  '/api/public/cron/scrape-bezrealitky': typeof ApiPublicCronScrapeBezrealitkyRoute
  '/api/public/cron/scrape-hyperinzerce': typeof ApiPublicCronScrapeHyperinzerceRoute
  '/api/public/cron/scrape-idnes': typeof ApiPublicCronScrapeIdnesRoute
  '/api/public/cron/scrape-realitymix': typeof ApiPublicCronScrapeRealitymixRoute
  '/api/public/cron/scrape-sreality': typeof ApiPublicCronScrapeSrealityRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cenik': typeof CenikRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/health': typeof AuthenticatedHealthRoute
  '/nastaveni-investora': typeof AuthenticatedNastaveniInvestoraRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/watchdogs': typeof AuthenticatedWatchdogsRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/scrape-annonce': typeof ApiPublicCronScrapeAnnonceRoute
  '/api/public/cron/scrape-bazos': typeof ApiPublicCronScrapeBazosRoute
  '/api/public/cron/scrape-bezrealitky': typeof ApiPublicCronScrapeBezrealitkyRoute
  '/api/public/cron/scrape-hyperinzerce': typeof ApiPublicCronScrapeHyperinzerceRoute
  '/api/public/cron/scrape-idnes': typeof ApiPublicCronScrapeIdnesRoute
  '/api/public/cron/scrape-realitymix': typeof ApiPublicCronScrapeRealitymixRoute
  '/api/public/cron/scrape-sreality': typeof ApiPublicCronScrapeSrealityRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cenik': typeof CenikRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/nastaveni-investora': typeof AuthenticatedNastaveniInvestoraRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/watchdogs': typeof AuthenticatedWatchdogsRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/scrape-annonce': typeof ApiPublicCronScrapeAnnonceRoute
  '/api/public/cron/scrape-bazos': typeof ApiPublicCronScrapeBazosRoute
  '/api/public/cron/scrape-bezrealitky': typeof ApiPublicCronScrapeBezrealitkyRoute
  '/api/public/cron/scrape-hyperinzerce': typeof ApiPublicCronScrapeHyperinzerceRoute
  '/api/public/cron/scrape-idnes': typeof ApiPublicCronScrapeIdnesRoute
  '/api/public/cron/scrape-realitymix': typeof ApiPublicCronScrapeRealitymixRoute
  '/api/public/cron/scrape-sreality': typeof ApiPublicCronScrapeSrealityRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cenik'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/health'
    | '/nastaveni-investora'
    | '/saved'
    | '/watchdogs'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/health-check'
    | '/api/public/cron/scrape-annonce'
    | '/api/public/cron/scrape-bazos'
    | '/api/public/cron/scrape-bezrealitky'
    | '/api/public/cron/scrape-hyperinzerce'
    | '/api/public/cron/scrape-idnes'
    | '/api/public/cron/scrape-realitymix'
    | '/api/public/cron/scrape-sreality'
    | '/api/public/hooks/run-schedules'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cenik'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/health'
    | '/nastaveni-investora'
    | '/saved'
    | '/watchdogs'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/health-check'
    | '/api/public/cron/scrape-annonce'
    | '/api/public/cron/scrape-bazos'
    | '/api/public/cron/scrape-bezrealitky'
    | '/api/public/cron/scrape-hyperinzerce'
    | '/api/public/cron/scrape-idnes'
    | '/api/public/cron/scrape-realitymix'
    | '/api/public/cron/scrape-sreality'
    | '/api/public/hooks/run-schedules'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cenik'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/_authenticated/health'
    | '/_authenticated/nastaveni-investora'
    | '/_authenticated/saved'
    | '/_authenticated/watchdogs'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/health-check'
    | '/api/public/cron/scrape-annonce'
    | '/api/public/cron/scrape-bazos'
    | '/api/public/cron/scrape-bezrealitky'
    | '/api/public/cron/scrape-hyperinzerce'
    | '/api/public/cron/scrape-idnes'
    | '/api/public/cron/scrape-realitymix'
    | '/api/public/cron/scrape-sreality'
    | '/api/public/hooks/run-schedules'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CenikRoute: typeof CenikRoute
  ObchodniPodminkyRoute: typeof ObchodniPodminkyRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  ApiPublicCronDailyDigestRoute: typeof ApiPublicCronDailyDigestRoute
  ApiPublicCronHealthCheckRoute: typeof ApiPublicCronHealthCheckRoute
  ApiPublicCronScrapeAnnonceRoute: typeof ApiPublicCronScrapeAnnonceRoute
  ApiPublicCronScrapeBazosRoute: typeof ApiPublicCronScrapeBazosRoute
  ApiPublicCronScrapeBezrealitkyRoute: typeof ApiPublicCronScrapeBezrealitkyRoute
  ApiPublicCronScrapeHyperinzerceRoute: typeof ApiPublicCronScrapeHyperinzerceRoute
  ApiPublicCronScrapeIdnesRoute: typeof ApiPublicCronScrapeIdnesRoute
  ApiPublicCronScrapeRealitymixRoute: typeof ApiPublicCronScrapeRealitymixRoute
  ApiPublicCronScrapeSrealityRoute: typeof ApiPublicCronScrapeSrealityRoute
  ApiPublicHooksRunSchedulesRoute: typeof ApiPublicHooksRunSchedulesRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodni-podminky': {
      id: '/obchodni-podminky'
      path: '/obchodni-podminky'
      fullPath: '/obchodni-podminky'
      preLoaderRoute: typeof ObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchdogs': {
      id: '/_authenticated/watchdogs'
      path: '/watchdogs'
      fullPath: '/watchdogs'
      preLoaderRoute: typeof AuthenticatedWatchdogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nastaveni-investora': {
      id: '/_authenticated/nastaveni-investora'
      path: '/nastaveni-investora'
      fullPath: '/nastaveni-investora'
      preLoaderRoute: typeof AuthenticatedNastaveniInvestoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-schedules': {
      id: '/api/public/hooks/run-schedules'
      path: '/api/public/hooks/run-schedules'
      fullPath: '/api/public/hooks/run-schedules'
      preLoaderRoute: typeof ApiPublicHooksRunSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-sreality': {
      id: '/api/public/cron/scrape-sreality'
      path: '/api/public/cron/scrape-sreality'
      fullPath: '/api/public/cron/scrape-sreality'
      preLoaderRoute: typeof ApiPublicCronScrapeSrealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-realitymix': {
      id: '/api/public/cron/scrape-realitymix'
      path: '/api/public/cron/scrape-realitymix'
      fullPath: '/api/public/cron/scrape-realitymix'
      preLoaderRoute: typeof ApiPublicCronScrapeRealitymixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-idnes': {
      id: '/api/public/cron/scrape-idnes'
      path: '/api/public/cron/scrape-idnes'
      fullPath: '/api/public/cron/scrape-idnes'
      preLoaderRoute: typeof ApiPublicCronScrapeIdnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-hyperinzerce': {
      id: '/api/public/cron/scrape-hyperinzerce'
      path: '/api/public/cron/scrape-hyperinzerce'
      fullPath: '/api/public/cron/scrape-hyperinzerce'
      preLoaderRoute: typeof ApiPublicCronScrapeHyperinzerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-bezrealitky': {
      id: '/api/public/cron/scrape-bezrealitky'
      path: '/api/public/cron/scrape-bezrealitky'
      fullPath: '/api/public/cron/scrape-bezrealitky'
      preLoaderRoute: typeof ApiPublicCronScrapeBezrealitkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-bazos': {
      id: '/api/public/cron/scrape-bazos'
      path: '/api/public/cron/scrape-bazos'
      fullPath: '/api/public/cron/scrape-bazos'
      preLoaderRoute: typeof ApiPublicCronScrapeBazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-annonce': {
      id: '/api/public/cron/scrape-annonce'
      path: '/api/public/cron/scrape-annonce'
      fullPath: '/api/public/cron/scrape-annonce'
      preLoaderRoute: typeof ApiPublicCronScrapeAnnonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/health-check': {
      id: '/api/public/cron/health-check'
      path: '/api/public/cron/health-check'
      fullPath: '/api/public/cron/health-check'
      preLoaderRoute: typeof ApiPublicCronHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-digest': {
      id: '/api/public/cron/daily-digest'
      path: '/api/public/cron/daily-digest'
      fullPath: '/api/public/cron/daily-digest'
      preLoaderRoute: typeof ApiPublicCronDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedNastaveniInvestoraRoute: typeof AuthenticatedNastaveniInvestoraRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedWatchdogsRoute: typeof AuthenticatedWatchdogsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedNastaveniInvestoraRoute: AuthenticatedNastaveniInvestoraRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedWatchdogsRoute: AuthenticatedWatchdogsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CenikRoute: CenikRoute,
  ObchodniPodminkyRoute: ObchodniPodminkyRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  ApiPublicCronDailyDigestRoute: ApiPublicCronDailyDigestRoute,
  ApiPublicCronHealthCheckRoute: ApiPublicCronHealthCheckRoute,
  ApiPublicCronScrapeAnnonceRoute: ApiPublicCronScrapeAnnonceRoute,
  ApiPublicCronScrapeBazosRoute: ApiPublicCronScrapeBazosRoute,
  ApiPublicCronScrapeBezrealitkyRoute: ApiPublicCronScrapeBezrealitkyRoute,
  ApiPublicCronScrapeHyperinzerceRoute: ApiPublicCronScrapeHyperinzerceRoute,
  ApiPublicCronScrapeIdnesRoute: ApiPublicCronScrapeIdnesRoute,
  ApiPublicCronScrapeRealitymixRoute: ApiPublicCronScrapeRealitymixRoute,
  ApiPublicCronScrapeSrealityRoute: ApiPublicCronScrapeSrealityRoute,
  ApiPublicHooksRunSchedulesRoute: ApiPublicHooksRunSchedulesRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
