/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SrealityVsBezrealitkySrovnaniRouteImport } from './routes/sreality-vs-bezrealitky-srovnani'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as ObchodniPodminkyRouteImport } from './routes/obchodni-podminky'
import { Route as MetodikaRouteImport } from './routes/metodika'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KolikVydelavaByt2kkBrnoRouteImport } from './routes/kolik-vydelava-byt-2kk-brno'
import { Route as KdeKoupitInvesticniByt2026RouteImport } from './routes/kde-koupit-investicni-byt-2026'
import { Route as KalkulackaVynosuRouteImport } from './routes/kalkulacka-vynosu'
import { Route as JakPoznatPredrazenyBytRouteImport } from './routes/jak-poznat-predrazeny-byt'
import { Route as InvesticniNemovitostiRouteImport } from './routes/investicni-nemovitosti'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as R5ChybInvestoraDoNemovitostiRouteImport } from './routes/5-chyb-investora-do-nemovitosti'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWatchdogsRouteImport } from './routes/_authenticated/watchdogs'
import { Route as AuthenticatedUlozeneRouteImport } from './routes/_authenticated/ulozene'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedNastaveniInvestoraRouteImport } from './routes/_authenticated/nastaveni-investora'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicHooksRunSchedulesRouteImport } from './routes/api/public/hooks/run-schedules'
import { Route as ApiPublicCronScrapeSrealityRouteImport } from './routes/api/public/cron/scrape-sreality'
import { Route as ApiPublicCronScrapeRealitymixRouteImport } from './routes/api/public/cron/scrape-realitymix'
import { Route as ApiPublicCronScrapeIdnesRouteImport } from './routes/api/public/cron/scrape-idnes'
import { Route as ApiPublicCronScrapeHyperinzerceRouteImport } from './routes/api/public/cron/scrape-hyperinzerce'
import { Route as ApiPublicCronScrapeBezrealitkyRouteImport } from './routes/api/public/cron/scrape-bezrealitky'
import { Route as ApiPublicCronScrapeBazosRouteImport } from './routes/api/public/cron/scrape-bazos'
import { Route as ApiPublicCronScrapeAnnonceRouteImport } from './routes/api/public/cron/scrape-annonce'
import { Route as ApiPublicCronHealthCheckRouteImport } from './routes/api/public/cron/health-check'
import { Route as ApiPublicCronDailyDigestRouteImport } from './routes/api/public/cron/daily-digest'
import { Route as ApiPublicCronCsuCalibrationRouteImport } from './routes/api/public/cron/csu-calibration'

const SrealityVsBezrealitkySrovnaniRoute =
  SrealityVsBezrealitkySrovnaniRouteImport.update({
    id: '/sreality-vs-bezrealitky-srovnani',
    path: '/sreality-vs-bezrealitky-srovnani',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodniPodminkyRoute = ObchodniPodminkyRouteImport.update({
  id: '/obchodni-podminky',
  path: '/obchodni-podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodikaRoute = MetodikaRouteImport.update({
  id: '/metodika',
  path: '/metodika',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KolikVydelavaByt2kkBrnoRoute = KolikVydelavaByt2kkBrnoRouteImport.update({
  id: '/kolik-vydelava-byt-2kk-brno',
  path: '/kolik-vydelava-byt-2kk-brno',
  getParentRoute: () => rootRouteImport,
} as any)
const KdeKoupitInvesticniByt2026Route =
  KdeKoupitInvesticniByt2026RouteImport.update({
    id: '/kde-koupit-investicni-byt-2026',
    path: '/kde-koupit-investicni-byt-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const KalkulackaVynosuRoute = KalkulackaVynosuRouteImport.update({
  id: '/kalkulacka-vynosu',
  path: '/kalkulacka-vynosu',
  getParentRoute: () => rootRouteImport,
} as any)
const JakPoznatPredrazenyBytRoute = JakPoznatPredrazenyBytRouteImport.update({
  id: '/jak-poznat-predrazeny-byt',
  path: '/jak-poznat-predrazeny-byt',
  getParentRoute: () => rootRouteImport,
} as any)
const InvesticniNemovitostiRoute = InvesticniNemovitostiRouteImport.update({
  id: '/investicni-nemovitosti',
  path: '/investicni-nemovitosti',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R5ChybInvestoraDoNemovitostiRoute =
  R5ChybInvestoraDoNemovitostiRouteImport.update({
    id: '/5-chyb-investora-do-nemovitosti',
    path: '/5-chyb-investora-do-nemovitosti',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchdogsRoute = AuthenticatedWatchdogsRouteImport.update({
  id: '/watchdogs',
  path: '/watchdogs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUlozeneRoute = AuthenticatedUlozeneRouteImport.update({
  id: '/ulozene',
  path: '/ulozene',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNastaveniInvestoraRoute =
  AuthenticatedNastaveniInvestoraRouteImport.update({
    id: '/nastaveni-investora',
    path: '/nastaveni-investora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunSchedulesRoute =
  ApiPublicHooksRunSchedulesRouteImport.update({
    id: '/api/public/hooks/run-schedules',
    path: '/api/public/hooks/run-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeSrealityRoute =
  ApiPublicCronScrapeSrealityRouteImport.update({
    id: '/api/public/cron/scrape-sreality',
    path: '/api/public/cron/scrape-sreality',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeRealitymixRoute =
  ApiPublicCronScrapeRealitymixRouteImport.update({
    id: '/api/public/cron/scrape-realitymix',
    path: '/api/public/cron/scrape-realitymix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeIdnesRoute =
  ApiPublicCronScrapeIdnesRouteImport.update({
    id: '/api/public/cron/scrape-idnes',
    path: '/api/public/cron/scrape-idnes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeHyperinzerceRoute =
  ApiPublicCronScrapeHyperinzerceRouteImport.update({
    id: '/api/public/cron/scrape-hyperinzerce',
    path: '/api/public/cron/scrape-hyperinzerce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeBezrealitkyRoute =
  ApiPublicCronScrapeBezrealitkyRouteImport.update({
    id: '/api/public/cron/scrape-bezrealitky',
    path: '/api/public/cron/scrape-bezrealitky',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeBazosRoute =
  ApiPublicCronScrapeBazosRouteImport.update({
    id: '/api/public/cron/scrape-bazos',
    path: '/api/public/cron/scrape-bazos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronScrapeAnnonceRoute =
  ApiPublicCronScrapeAnnonceRouteImport.update({
    id: '/api/public/cron/scrape-annonce',
    path: '/api/public/cron/scrape-annonce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHealthCheckRoute =
  ApiPublicCronHealthCheckRouteImport.update({
    id: '/api/public/cron/health-check',
    path: '/api/public/cron/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyDigestRoute =
  ApiPublicCronDailyDigestRouteImport.update({
    id: '/api/public/cron/daily-digest',
    path: '/api/public/cron/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCsuCalibrationRoute =
  ApiPublicCronCsuCalibrationRouteImport.update({
    id: '/api/public/cron/csu-calibration',
    path: '/api/public/cron/csu-calibration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/5-chyb-investora-do-nemovitosti': typeof R5ChybInvestoraDoNemovitostiRoute
  '/auth': typeof AuthRoute
  '/cenik': typeof CenikRoute
  '/investicni-nemovitosti': typeof InvesticniNemovitostiRoute
  '/jak-poznat-predrazeny-byt': typeof JakPoznatPredrazenyBytRoute
  '/kalkulacka-vynosu': typeof KalkulackaVynosuRoute
  '/kde-koupit-investicni-byt-2026': typeof KdeKoupitInvesticniByt2026Route
  '/kolik-vydelava-byt-2kk-brno': typeof KolikVydelavaByt2kkBrnoRoute
  '/kontakt': typeof KontaktRoute
  '/metodika': typeof MetodikaRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sreality-vs-bezrealitky-srovnani': typeof SrealityVsBezrealitkySrovnaniRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/health': typeof AuthenticatedHealthRoute
  '/nastaveni-investora': typeof AuthenticatedNastaveniInvestoraRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/ulozene': typeof AuthenticatedUlozeneRoute
  '/watchdogs': typeof AuthenticatedWatchdogsRoute
  '/api/public/cron/csu-calibration': typeof ApiPublicCronCsuCalibrationRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/scrape-annonce': typeof ApiPublicCronScrapeAnnonceRoute
  '/api/public/cron/scrape-bazos': typeof ApiPublicCronScrapeBazosRoute
  '/api/public/cron/scrape-bezrealitky': typeof ApiPublicCronScrapeBezrealitkyRoute
  '/api/public/cron/scrape-hyperinzerce': typeof ApiPublicCronScrapeHyperinzerceRoute
  '/api/public/cron/scrape-idnes': typeof ApiPublicCronScrapeIdnesRoute
  '/api/public/cron/scrape-realitymix': typeof ApiPublicCronScrapeRealitymixRoute
  '/api/public/cron/scrape-sreality': typeof ApiPublicCronScrapeSrealityRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/5-chyb-investora-do-nemovitosti': typeof R5ChybInvestoraDoNemovitostiRoute
  '/auth': typeof AuthRoute
  '/cenik': typeof CenikRoute
  '/investicni-nemovitosti': typeof InvesticniNemovitostiRoute
  '/jak-poznat-predrazeny-byt': typeof JakPoznatPredrazenyBytRoute
  '/kalkulacka-vynosu': typeof KalkulackaVynosuRoute
  '/kde-koupit-investicni-byt-2026': typeof KdeKoupitInvesticniByt2026Route
  '/kolik-vydelava-byt-2kk-brno': typeof KolikVydelavaByt2kkBrnoRoute
  '/kontakt': typeof KontaktRoute
  '/metodika': typeof MetodikaRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sreality-vs-bezrealitky-srovnani': typeof SrealityVsBezrealitkySrovnaniRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/health': typeof AuthenticatedHealthRoute
  '/nastaveni-investora': typeof AuthenticatedNastaveniInvestoraRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/ulozene': typeof AuthenticatedUlozeneRoute
  '/watchdogs': typeof AuthenticatedWatchdogsRoute
  '/api/public/cron/csu-calibration': typeof ApiPublicCronCsuCalibrationRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/scrape-annonce': typeof ApiPublicCronScrapeAnnonceRoute
  '/api/public/cron/scrape-bazos': typeof ApiPublicCronScrapeBazosRoute
  '/api/public/cron/scrape-bezrealitky': typeof ApiPublicCronScrapeBezrealitkyRoute
  '/api/public/cron/scrape-hyperinzerce': typeof ApiPublicCronScrapeHyperinzerceRoute
  '/api/public/cron/scrape-idnes': typeof ApiPublicCronScrapeIdnesRoute
  '/api/public/cron/scrape-realitymix': typeof ApiPublicCronScrapeRealitymixRoute
  '/api/public/cron/scrape-sreality': typeof ApiPublicCronScrapeSrealityRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/5-chyb-investora-do-nemovitosti': typeof R5ChybInvestoraDoNemovitostiRoute
  '/auth': typeof AuthRoute
  '/cenik': typeof CenikRoute
  '/investicni-nemovitosti': typeof InvesticniNemovitostiRoute
  '/jak-poznat-predrazeny-byt': typeof JakPoznatPredrazenyBytRoute
  '/kalkulacka-vynosu': typeof KalkulackaVynosuRoute
  '/kde-koupit-investicni-byt-2026': typeof KdeKoupitInvesticniByt2026Route
  '/kolik-vydelava-byt-2kk-brno': typeof KolikVydelavaByt2kkBrnoRoute
  '/kontakt': typeof KontaktRoute
  '/metodika': typeof MetodikaRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sreality-vs-bezrealitky-srovnani': typeof SrealityVsBezrealitkySrovnaniRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/nastaveni-investora': typeof AuthenticatedNastaveniInvestoraRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/ulozene': typeof AuthenticatedUlozeneRoute
  '/_authenticated/watchdogs': typeof AuthenticatedWatchdogsRoute
  '/api/public/cron/csu-calibration': typeof ApiPublicCronCsuCalibrationRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/health-check': typeof ApiPublicCronHealthCheckRoute
  '/api/public/cron/scrape-annonce': typeof ApiPublicCronScrapeAnnonceRoute
  '/api/public/cron/scrape-bazos': typeof ApiPublicCronScrapeBazosRoute
  '/api/public/cron/scrape-bezrealitky': typeof ApiPublicCronScrapeBezrealitkyRoute
  '/api/public/cron/scrape-hyperinzerce': typeof ApiPublicCronScrapeHyperinzerceRoute
  '/api/public/cron/scrape-idnes': typeof ApiPublicCronScrapeIdnesRoute
  '/api/public/cron/scrape-realitymix': typeof ApiPublicCronScrapeRealitymixRoute
  '/api/public/cron/scrape-sreality': typeof ApiPublicCronScrapeSrealityRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/5-chyb-investora-do-nemovitosti'
    | '/auth'
    | '/cenik'
    | '/investicni-nemovitosti'
    | '/jak-poznat-predrazeny-byt'
    | '/kalkulacka-vynosu'
    | '/kde-koupit-investicni-byt-2026'
    | '/kolik-vydelava-byt-2kk-brno'
    | '/kontakt'
    | '/metodika'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/sitemap.xml'
    | '/sreality-vs-bezrealitky-srovnani'
    | '/admin'
    | '/health'
    | '/nastaveni-investora'
    | '/saved'
    | '/ulozene'
    | '/watchdogs'
    | '/api/public/cron/csu-calibration'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/health-check'
    | '/api/public/cron/scrape-annonce'
    | '/api/public/cron/scrape-bazos'
    | '/api/public/cron/scrape-bezrealitky'
    | '/api/public/cron/scrape-hyperinzerce'
    | '/api/public/cron/scrape-idnes'
    | '/api/public/cron/scrape-realitymix'
    | '/api/public/cron/scrape-sreality'
    | '/api/public/hooks/run-schedules'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/5-chyb-investora-do-nemovitosti'
    | '/auth'
    | '/cenik'
    | '/investicni-nemovitosti'
    | '/jak-poznat-predrazeny-byt'
    | '/kalkulacka-vynosu'
    | '/kde-koupit-investicni-byt-2026'
    | '/kolik-vydelava-byt-2kk-brno'
    | '/kontakt'
    | '/metodika'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/sitemap.xml'
    | '/sreality-vs-bezrealitky-srovnani'
    | '/admin'
    | '/health'
    | '/nastaveni-investora'
    | '/saved'
    | '/ulozene'
    | '/watchdogs'
    | '/api/public/cron/csu-calibration'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/health-check'
    | '/api/public/cron/scrape-annonce'
    | '/api/public/cron/scrape-bazos'
    | '/api/public/cron/scrape-bezrealitky'
    | '/api/public/cron/scrape-hyperinzerce'
    | '/api/public/cron/scrape-idnes'
    | '/api/public/cron/scrape-realitymix'
    | '/api/public/cron/scrape-sreality'
    | '/api/public/hooks/run-schedules'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/5-chyb-investora-do-nemovitosti'
    | '/auth'
    | '/cenik'
    | '/investicni-nemovitosti'
    | '/jak-poznat-predrazeny-byt'
    | '/kalkulacka-vynosu'
    | '/kde-koupit-investicni-byt-2026'
    | '/kolik-vydelava-byt-2kk-brno'
    | '/kontakt'
    | '/metodika'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/sitemap.xml'
    | '/sreality-vs-bezrealitky-srovnani'
    | '/_authenticated/admin'
    | '/_authenticated/health'
    | '/_authenticated/nastaveni-investora'
    | '/_authenticated/saved'
    | '/_authenticated/ulozene'
    | '/_authenticated/watchdogs'
    | '/api/public/cron/csu-calibration'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/health-check'
    | '/api/public/cron/scrape-annonce'
    | '/api/public/cron/scrape-bazos'
    | '/api/public/cron/scrape-bezrealitky'
    | '/api/public/cron/scrape-hyperinzerce'
    | '/api/public/cron/scrape-idnes'
    | '/api/public/cron/scrape-realitymix'
    | '/api/public/cron/scrape-sreality'
    | '/api/public/hooks/run-schedules'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R5ChybInvestoraDoNemovitostiRoute: typeof R5ChybInvestoraDoNemovitostiRoute
  AuthRoute: typeof AuthRoute
  CenikRoute: typeof CenikRoute
  InvesticniNemovitostiRoute: typeof InvesticniNemovitostiRoute
  JakPoznatPredrazenyBytRoute: typeof JakPoznatPredrazenyBytRoute
  KalkulackaVynosuRoute: typeof KalkulackaVynosuRoute
  KdeKoupitInvesticniByt2026Route: typeof KdeKoupitInvesticniByt2026Route
  KolikVydelavaByt2kkBrnoRoute: typeof KolikVydelavaByt2kkBrnoRoute
  KontaktRoute: typeof KontaktRoute
  MetodikaRoute: typeof MetodikaRoute
  ObchodniPodminkyRoute: typeof ObchodniPodminkyRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SrealityVsBezrealitkySrovnaniRoute: typeof SrealityVsBezrealitkySrovnaniRoute
  ApiPublicCronCsuCalibrationRoute: typeof ApiPublicCronCsuCalibrationRoute
  ApiPublicCronDailyDigestRoute: typeof ApiPublicCronDailyDigestRoute
  ApiPublicCronHealthCheckRoute: typeof ApiPublicCronHealthCheckRoute
  ApiPublicCronScrapeAnnonceRoute: typeof ApiPublicCronScrapeAnnonceRoute
  ApiPublicCronScrapeBazosRoute: typeof ApiPublicCronScrapeBazosRoute
  ApiPublicCronScrapeBezrealitkyRoute: typeof ApiPublicCronScrapeBezrealitkyRoute
  ApiPublicCronScrapeHyperinzerceRoute: typeof ApiPublicCronScrapeHyperinzerceRoute
  ApiPublicCronScrapeIdnesRoute: typeof ApiPublicCronScrapeIdnesRoute
  ApiPublicCronScrapeRealitymixRoute: typeof ApiPublicCronScrapeRealitymixRoute
  ApiPublicCronScrapeSrealityRoute: typeof ApiPublicCronScrapeSrealityRoute
  ApiPublicHooksRunSchedulesRoute: typeof ApiPublicHooksRunSchedulesRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sreality-vs-bezrealitky-srovnani': {
      id: '/sreality-vs-bezrealitky-srovnani'
      path: '/sreality-vs-bezrealitky-srovnani'
      fullPath: '/sreality-vs-bezrealitky-srovnani'
      preLoaderRoute: typeof SrealityVsBezrealitkySrovnaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodni-podminky': {
      id: '/obchodni-podminky'
      path: '/obchodni-podminky'
      fullPath: '/obchodni-podminky'
      preLoaderRoute: typeof ObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodika': {
      id: '/metodika'
      path: '/metodika'
      fullPath: '/metodika'
      preLoaderRoute: typeof MetodikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolik-vydelava-byt-2kk-brno': {
      id: '/kolik-vydelava-byt-2kk-brno'
      path: '/kolik-vydelava-byt-2kk-brno'
      fullPath: '/kolik-vydelava-byt-2kk-brno'
      preLoaderRoute: typeof KolikVydelavaByt2kkBrnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kde-koupit-investicni-byt-2026': {
      id: '/kde-koupit-investicni-byt-2026'
      path: '/kde-koupit-investicni-byt-2026'
      fullPath: '/kde-koupit-investicni-byt-2026'
      preLoaderRoute: typeof KdeKoupitInvesticniByt2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulacka-vynosu': {
      id: '/kalkulacka-vynosu'
      path: '/kalkulacka-vynosu'
      fullPath: '/kalkulacka-vynosu'
      preLoaderRoute: typeof KalkulackaVynosuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jak-poznat-predrazeny-byt': {
      id: '/jak-poznat-predrazeny-byt'
      path: '/jak-poznat-predrazeny-byt'
      fullPath: '/jak-poznat-predrazeny-byt'
      preLoaderRoute: typeof JakPoznatPredrazenyBytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investicni-nemovitosti': {
      id: '/investicni-nemovitosti'
      path: '/investicni-nemovitosti'
      fullPath: '/investicni-nemovitosti'
      preLoaderRoute: typeof InvesticniNemovitostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5-chyb-investora-do-nemovitosti': {
      id: '/5-chyb-investora-do-nemovitosti'
      path: '/5-chyb-investora-do-nemovitosti'
      fullPath: '/5-chyb-investora-do-nemovitosti'
      preLoaderRoute: typeof R5ChybInvestoraDoNemovitostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchdogs': {
      id: '/_authenticated/watchdogs'
      path: '/watchdogs'
      fullPath: '/watchdogs'
      preLoaderRoute: typeof AuthenticatedWatchdogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ulozene': {
      id: '/_authenticated/ulozene'
      path: '/ulozene'
      fullPath: '/ulozene'
      preLoaderRoute: typeof AuthenticatedUlozeneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nastaveni-investora': {
      id: '/_authenticated/nastaveni-investora'
      path: '/nastaveni-investora'
      fullPath: '/nastaveni-investora'
      preLoaderRoute: typeof AuthenticatedNastaveniInvestoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-schedules': {
      id: '/api/public/hooks/run-schedules'
      path: '/api/public/hooks/run-schedules'
      fullPath: '/api/public/hooks/run-schedules'
      preLoaderRoute: typeof ApiPublicHooksRunSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-sreality': {
      id: '/api/public/cron/scrape-sreality'
      path: '/api/public/cron/scrape-sreality'
      fullPath: '/api/public/cron/scrape-sreality'
      preLoaderRoute: typeof ApiPublicCronScrapeSrealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-realitymix': {
      id: '/api/public/cron/scrape-realitymix'
      path: '/api/public/cron/scrape-realitymix'
      fullPath: '/api/public/cron/scrape-realitymix'
      preLoaderRoute: typeof ApiPublicCronScrapeRealitymixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-idnes': {
      id: '/api/public/cron/scrape-idnes'
      path: '/api/public/cron/scrape-idnes'
      fullPath: '/api/public/cron/scrape-idnes'
      preLoaderRoute: typeof ApiPublicCronScrapeIdnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-hyperinzerce': {
      id: '/api/public/cron/scrape-hyperinzerce'
      path: '/api/public/cron/scrape-hyperinzerce'
      fullPath: '/api/public/cron/scrape-hyperinzerce'
      preLoaderRoute: typeof ApiPublicCronScrapeHyperinzerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-bezrealitky': {
      id: '/api/public/cron/scrape-bezrealitky'
      path: '/api/public/cron/scrape-bezrealitky'
      fullPath: '/api/public/cron/scrape-bezrealitky'
      preLoaderRoute: typeof ApiPublicCronScrapeBezrealitkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-bazos': {
      id: '/api/public/cron/scrape-bazos'
      path: '/api/public/cron/scrape-bazos'
      fullPath: '/api/public/cron/scrape-bazos'
      preLoaderRoute: typeof ApiPublicCronScrapeBazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-annonce': {
      id: '/api/public/cron/scrape-annonce'
      path: '/api/public/cron/scrape-annonce'
      fullPath: '/api/public/cron/scrape-annonce'
      preLoaderRoute: typeof ApiPublicCronScrapeAnnonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/health-check': {
      id: '/api/public/cron/health-check'
      path: '/api/public/cron/health-check'
      fullPath: '/api/public/cron/health-check'
      preLoaderRoute: typeof ApiPublicCronHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-digest': {
      id: '/api/public/cron/daily-digest'
      path: '/api/public/cron/daily-digest'
      fullPath: '/api/public/cron/daily-digest'
      preLoaderRoute: typeof ApiPublicCronDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/csu-calibration': {
      id: '/api/public/cron/csu-calibration'
      path: '/api/public/cron/csu-calibration'
      fullPath: '/api/public/cron/csu-calibration'
      preLoaderRoute: typeof ApiPublicCronCsuCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedNastaveniInvestoraRoute: typeof AuthenticatedNastaveniInvestoraRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedUlozeneRoute: typeof AuthenticatedUlozeneRoute
  AuthenticatedWatchdogsRoute: typeof AuthenticatedWatchdogsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedNastaveniInvestoraRoute: AuthenticatedNastaveniInvestoraRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedUlozeneRoute: AuthenticatedUlozeneRoute,
  AuthenticatedWatchdogsRoute: AuthenticatedWatchdogsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R5ChybInvestoraDoNemovitostiRoute: R5ChybInvestoraDoNemovitostiRoute,
  AuthRoute: AuthRoute,
  CenikRoute: CenikRoute,
  InvesticniNemovitostiRoute: InvesticniNemovitostiRoute,
  JakPoznatPredrazenyBytRoute: JakPoznatPredrazenyBytRoute,
  KalkulackaVynosuRoute: KalkulackaVynosuRoute,
  KdeKoupitInvesticniByt2026Route: KdeKoupitInvesticniByt2026Route,
  KolikVydelavaByt2kkBrnoRoute: KolikVydelavaByt2kkBrnoRoute,
  KontaktRoute: KontaktRoute,
  MetodikaRoute: MetodikaRoute,
  ObchodniPodminkyRoute: ObchodniPodminkyRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SrealityVsBezrealitkySrovnaniRoute: SrealityVsBezrealitkySrovnaniRoute,
  ApiPublicCronCsuCalibrationRoute: ApiPublicCronCsuCalibrationRoute,
  ApiPublicCronDailyDigestRoute: ApiPublicCronDailyDigestRoute,
  ApiPublicCronHealthCheckRoute: ApiPublicCronHealthCheckRoute,
  ApiPublicCronScrapeAnnonceRoute: ApiPublicCronScrapeAnnonceRoute,
  ApiPublicCronScrapeBazosRoute: ApiPublicCronScrapeBazosRoute,
  ApiPublicCronScrapeBezrealitkyRoute: ApiPublicCronScrapeBezrealitkyRoute,
  ApiPublicCronScrapeHyperinzerceRoute: ApiPublicCronScrapeHyperinzerceRoute,
  ApiPublicCronScrapeIdnesRoute: ApiPublicCronScrapeIdnesRoute,
  ApiPublicCronScrapeRealitymixRoute: ApiPublicCronScrapeRealitymixRoute,
  ApiPublicCronScrapeSrealityRoute: ApiPublicCronScrapeSrealityRoute,
  ApiPublicHooksRunSchedulesRoute: ApiPublicHooksRunSchedulesRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
